install.packages("shiny")
install.packages("shinyWidgets")
install.packages("bslib")
install.packages("dplyr")
install.packages("readr")
install.packages("leaflet")
install.packages("sf")
install.packages("tigris")

library(shiny)
library(shinyWidgets)
library(bslib)
library(dplyr)
library(readr)
library(leaflet)
library(sf)
library(tigris)